### ISSUE TITLE
Broken with gedit 3.20 

### ISSUE THREAD

**Issue by fedsib** [ilmanzo/gedit-plugin-gulpease#1]
Traceback (most recent call last):
  File "/home/user/.local/share/gedit/plugins/leggibilita.py", line 30, in do_activate
    self._add_ui()
  File "/home/user/.local/share/gedit/plugins/leggibilita.py", line 20, in _add_ui
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
Traceback (most recent call last):
  File "/home/user/.local/share/gedit/plugins/leggibilita.py", line 33, in do_deactivate
    self._remove_ui()
  File "/home/user/.local/share/gedit/plugins/leggibilita.py", line 60, in _remove_ui
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'

**Comment by ilmanzo** [comment]
unfortunately plugin API has changed with Gedit 3.x ; new specs are documented here: https://wiki.gnome.org/Apps/Gedit/PythonPluginHowTo .  I need some time to convert the code, but if you want to contribute with a pull request you're welcome :)

**Comment by ilmanzo** [comment]
other good starting point for porting: https://theawless.github.io/How-to-write-plugins-for-gedit/

**Comment by ilmanzo** [comment]
updated to the new plugin API
